# VSCode extensions

```
bbenoist.shell
benawad.VSinder
bierner.markdown-preview-github-styles
bradlc.vscode-tailwindcss
burkeholland.simple-react-snippets
bysabi.prettier-vscode-standard
christian-kohler.path-intellisense
DavidAnson.vscode-markdownlint
dbaeumer.vscode-eslint
drcallaway.vscode-surround-with
eamodio.gitlens
ecmel.vscode-html-css
eg2.vscode-npm-script
esbenp.prettier-vscode
fauna.faunadb
foxundermoon.shell-format
GitHub.vscode-pull-request-github
GraphQL.vscode-graphql
jeremyrajan.vscode-lebab
kamikillerto.vscode-colorize
Koihik.vscode-lua-format
meganrogge.template-string-converter
ms-vscode.vscode-typescript-next
ms-vscode.vscode-typescript-tslint-plugin
mtxr.sqltools
naumovs.color-highlight
pranaygp.vscode-css-peek
redhat.vscode-xml
riazxrazor.html-to-jsx
ritwickdey.LiveServer
sburg.vscode-javascript-booster
SimonSiefke.html-language-features
streetsidesoftware.code-spell-checker
tamj0rd2.ts-quickfixes-extension
WakaTime.vscode-wakatime
wix.vscode-import-cost
Zignd.html-css-class-completion
```
